#! /bin/bash

set -e
set -u
set -x

python setup.py test -t test/unit -v
python setup.py test -t test/integration -v -m "not slowtest"
python setup.py sdist install
pip install dist/*.tar.gz
omego version
omego -h



#Install a new server without web
#Tests rely on a non-zero error code being returned on failure
if [ $TEST = install ]; then
  export OMERODIR='./OMERO.server-5.6.4-ice36-b232'
  omego install --github ome/openmicroscopy --initdb --dbhost localhost --dbname omero --prestartfile $HOME/config.omero -v --release 5.6.4 --no-web --no-start

  ls OMERO.server
  # Should return 0 DB_UPTODATE
  omego db upgrade -n --dbhost localhost --dbname omero --serverdir OMERO.server

  # Check the expected server version was downloaded
  test $(readlink OMERO.server) = $OMERODIR

  # Check db dump file
  omego db dump --serverdir OMERO.server --dumpfile omero.pgdump
  
  pg_restore -l omero.pgdump | grep 'dbpatch_versions_trigger'
fi

#Test a multistage DB upgrade (5.3 -> 5.4) as part of the server upgrade
if [ $TEST = upgrade ]; then
  omego download --github ome/openmicroscopy --release 5.3 server
  ln -s OMERO.server-5.3.5-ice36-b73 OMERO.server;

  # Should return 3 DB_INIT_NEEDED
  RC=0;
  omego db upgrade -n --dbname omero --serverdir OMERO.server || RC=$?
  test $RC -eq 3

  OMERO.server/bin/omero db script "" "" ome -f OMERO.sql;
  psql -q -h localhost -U omero omero < OMERO.sql;
  OMERO.server/bin/omero load $HOME/config.omero;
  OMERO.server/bin/omero admin start;

  # Should return 0 DB_UPTODATE
  omego db upgrade -n --serverdir OMERO.server

  omego download --github ome/openmicroscopy --release 5.5 server --sym download-server-50
  # Should return 2 DB_UPGRADE_NEEDED
  RC=0;
  omego db upgrade -n --dbname omero --serverdir download-server-50 || RC=$?
  test $RC -eq 2

  # Note this should use the already downloaded zip from the previous step
  omego install --upgrade --managedb --release=5.5 --ice 3.6 --no-web

  # Should return 0 DB_UPTODATE
  omego db upgrade -n --serverdir OMERO.server
fi
