#! /bin/bash

set -e
set -u
set -x

# Install Ice 3.5 from custom build (since VMs are still 12.04 based)
echo -e "travis_fold:start:ice.install\r"
mkdir -p download
cd download
wget --user-agent $USER_AGENT http://downloads.openmicroscopy.org/ice/experimental/Ice-3.5.1-b1-ubuntu1204-amd64.tar.xz
cd ..
tar -xf "download/Ice-3.5.1-b1-ubuntu1204-amd64.tar.xz"
ICE_HOME="$(pwd)/Ice-3.5.1-b1-ubuntu1204-amd64"
export SLICEPATH="${ICE_HOME}/slice"
export PATH="${ICE_HOME}/bin:$PATH"
export LD_LIBRARY_PATH="${ICE_HOME}/lib"
export PYTHONPATH="${ICE_HOME}/python"
echo -e "travis_fold:end:ice.install\r"

python setup.py test -t test/unit -v
python setup.py test -t test/integration -v -m "not slowtest"
python setup.py sdist install
pip install dist/*.tar.gz
omego version
omego -h

#Install a new server
#Tests rely on a non-zero error code being returned on failure
if [ $TEST = install ]; then
  omego install --initdb --dbhost localhost --dbname omero --prestartfile $HOME/config.omero -v --release 5.0.8 --ice 3.5

  # Check the expected server version was downloaded
  test $(readlink OMERO-CURRENT) = './OMERO.server-5.0.8-ice35-b60'

  # Check db dump file
  omego db dump --serverdir OMERO-CURRENT --dumpfile travis-omero.pgdump
  pg_restore -e travis-omero.pgdump | grep 'CREATE TABLE dbpatch'
fi

#Test a multistage DB upgrade (4.4 -> 5.2) as part of the server upgrade
if [ $TEST = upgrade ]; then
  omego download --release 4 --ice 3.5 server
  ln -s OMERO.server-4.4.12-ice35-b116 OMERO-CURRENT;
  OMERO-CURRENT/bin/omero db script "" "" ome -f OMERO.sql;
  psql -q -h localhost -U omero omero < OMERO.sql;
  OMERO-CURRENT/bin/omero load $HOME/config.omero;
  OMERO-CURRENT/bin/omero admin start;
  omego upgrade --release=5.2 --ice 3.5 --upgradedb --no-web -v;
fi
