#! /bin/bash

set -eux

sudo apt-get update
sudo apt-get -y install python-{pillow,numpy,psutil}
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5E6DA83306132997
sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu`lsb_release -rs` stable main"
sudo apt-get update
sudo apt-get -y install zeroc-ice-all-runtime zeroc-ice-all-dev

# The distribution Python 2.7 is still present when Travis is setup to use 3.6
# so we can use it to run OMERO
if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then
  pip install https://github.com/ome/zeroc-ice-py-manylinux/releases/download/0.1.0/zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl
  sudo pip2.7 install https://github.com/ome/zeroc-ice-py-manylinux/releases/download/0.1.0/zeroc_ice-3.6.5-cp27-cp27mu-manylinux2010_x86_64.whl

  python3.6 -c 'import Ice; print(Ice.stringVersion())'
  python2.7 -c 'import Ice; print(Ice.stringVersion())'
else
  pip install https://github.com/ome/zeroc-ice-py-manylinux/releases/download/0.1.0/zeroc_ice-3.6.5-cp27-cp27mu-manylinux2010_x86_64.whl

  python -c 'import Ice; print(Ice.stringVersion())'
fi
