#! /bin/bash

set -eux

sudo apt-get update
sudo apt-get -y install python-{pillow,numpy,psutil}

pushd /opt
curl -sfL https://github.com/ome/zeroc-ice-ubuntu1804/releases/download/0.3.0/ice-3.6.5-0.3.0-ubuntu1804-amd64.tar.gz | sudo tar -zxf -
popd
sudo ln -s /opt/ice-3.6.5-0.3.0/bin/* /usr/local/bin/

# The distribution Python 2.7 is still present when Travis is setup to use 3.6
# so we can use it to run OMERO

if [ "${TRAVIS_PYTHON_VERSION:-}" = "2.7" ]; then
  export PATH=/usr/bin/:$PATH
fi

if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then
  pip install https://github.com/ome/zeroc-ice-py-manylinux/releases/download/0.3.0/zeroc_ice-3.6.5-cp36-cp36m-manylinux2014_x86_64.whl
  python3 -c 'import Ice; print(Ice.stringVersion())'
fi
sudo pip2.7 install https://github.com/ome/zeroc-ice-py-manylinux/releases/download/0.2.0/zeroc_ice-3.6.5-cp27-cp27mu-manylinux2010_x86_64.whl
python2.7 -c 'import Ice; print(Ice.stringVersion())'
