[PlateType]
Description=Imaging [353219]
Brand=BD Falcon
Wells=96
[10X Olympus]
LaserFocusAchievable=1
LaserAFOffsets=60.000000
LaserAFDisplacement=150.000000
LaserGain=6
LaserDataFrequencyHz=30000
LaserDataPoints=8000
LaserAlgorithmType=2
Algo_SimpleThresh_Percentage=20
Algo_SimpleThresh_RollingAveWidth=50
Algo_DownTrend_Limit=4
Algo_DownTrend_Sensitivity=0.600000
SimpleThreshold_Algo_RollingAveWidth=50
SimpleThreshold_Algo_UseSmoothing=0
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
DoubleThreshold_Algo_RollingAveWidth=50
DoubleThreshold_Algo_UseSmoothing=1
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[20X LWD Olympus]
LaserFocusAchievable=0
LaserAFOffsets=3.000000
LaserAFDisplacement=3.000000
LaserGain=20
LaserDataFrequencyHz=12000
LaserDataPoints=6000
LaserAlgorithmType=0
Algo_SimpleThresh_Percentage=15
Algo_SimpleThresh_RollingAveWidth=200
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
SimpleThreshold_Algo_RollingAveWidth=200
SimpleThreshold_Algo_UseSmoothing=0
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=0
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[20X NA 075 Olympus]
LaserFocusAchievable=1
LaserAFOffsets=0.500000
LaserAFDisplacement=200.000000
LaserGain=9
LaserDataFrequencyHz=12000
LaserDataPoints=2000
LaserAlgorithmType=2
Algo_SimpleThresh_Percentage=40
Algo_SimpleThresh_RollingAveWidth=20
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
SimpleThreshold_Algo_RollingAveWidth=20
SimpleThreshold_Algo_UseSmoothing=0
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=1
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[40X LWD Olympus]
LaserFocusAchievable=1
LaserAFOffsets=0.000000
LaserAFDisplacement=0.000000
LaserGain=15
LaserDataFrequencyHz=12000
LaserDataPoints=3000
LaserAlgorithmType=0
Algo_SimpleThresh_Percentage=15
Algo_SimpleThresh_RollingAveWidth=200
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
SimpleThreshold_Algo_RollingAveWidth=200
SimpleThreshold_Algo_UseSmoothing=0
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=0
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[40X Olympus]
LaserFocusAchievable=1
LaserAFOffsets=0.280000
LaserAFDisplacement=100.000000
LaserGain=70
LaserDataFrequencyHz=12000
LaserDataPoints=2000
LaserAlgorithmType=2
Algo_SimpleThresh_Percentage=18
Algo_SimpleThresh_RollingAveWidth=50
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
SimpleThreshold_Algo_RollingAveWidth=50
SimpleThreshold_Algo_UseSmoothing=0
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=1
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[4X Olympus]
LaserFocusAchievable=1
LaserAFOffsets=0.000000
LaserAFDisplacement=0.000000
LaserGain=0
LaserDataFrequencyHz=12000
LaserDataPoints=6000
LaserAlgorithmType=0
Algo_SimpleThresh_Percentage=15
Algo_SimpleThresh_RollingAveWidth=200
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
SimpleThreshold_Algo_RollingAveWidth=200
SimpleThreshold_Algo_UseSmoothing=0
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=0
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[60X Olympus]
LaserFocusAchievable=0
LaserAFOffsets=-5.000000
LaserAFDisplacement=100.000000
LaserGain=20
LaserDataFrequencyHz=12000
LaserDataPoints=2000
LaserAlgorithmType=0
Algo_SimpleThresh_Percentage=38
Algo_SimpleThresh_RollingAveWidth=10
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
SimpleThreshold_Algo_RollingAveWidth=10
SimpleThreshold_Algo_UseSmoothing=0
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=0
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[10 X Olympus]
LaserFocusAchievable=1
LaserAFOffsets=90.880000
LaserAFDisplacement=150.000000
LaserGain=0
LaserDataFrequencyHz=12000
LaserDataPoints=2000
LaserAlgorithmType=0
Algo_SimpleThresh_Percentage=25
Algo_SimpleThresh_RollingAveWidth=100
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
SimpleThreshold_Algo_RollingAveWidth=100
SimpleThreshold_Algo_UseSmoothing=0
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=0
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[20 X Low Olympus]
LaserFocusAchievable=0
LaserAFOffsets=0.000000
LaserAFDisplacement=0.000000
LaserGain=15
LaserDataFrequencyHz=12000
LaserDataPoints=3000
LaserAlgorithmType=2
Algo_SimpleThresh_Percentage=15
Algo_SimpleThresh_RollingAveWidth=200
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
SimpleThreshold_Algo_RollingAveWidth=200
SimpleThreshold_Algo_UseSmoothing=0
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=1
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[20X NA 075 Olympus Confocal]
LaserFocusAchievable=1
LaserAFOffsets=0.300000
LaserAFDisplacement=200.000000
LaserGain=15
LaserDataFrequencyHz=12000
LaserDataPoints=2000
LaserAlgorithmType=2
SimpleThreshold_Algo_RollingAveWidth=99
SimpleThreshold_Algo_UseSmoothing=0
Algo_SimpleThresh_Percentage=15
Algo_SimpleThresh_RollingAveWidth=99
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=0
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
[40X Olympus Confocal]
LaserFocusAchievable=1
LaserAFOffsets=0.000000
LaserAFDisplacement=0.000000
LaserGain=10
LaserDataFrequencyHz=12000
LaserDataPoints=4000
LaserAlgorithmType=0
SimpleThreshold_Algo_RollingAveWidth=20
SimpleThreshold_Algo_UseSmoothing=0
Algo_SimpleThresh_Percentage=15
Algo_SimpleThresh_RollingAveWidth=20
DownTrend_Algo_RollingAveWidth=20
DownTrend_Algo_UseSmoothing=0
Algo_DownTrend_Limit=5
Algo_DownTrend_Sensitivity=0.500000
DoubleThreshold_Algo_RollingAveWidth=20
DoubleThreshold_Algo_UseSmoothing=0
Shoulder Peak_Algo_RollingAveWidth=20
Shoulder Peak_Algo_UseSmoothing=0
